version: "2.1"
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=nightcom
      - PGID=nightcom
      - TZ=Europe/London
      - UMASK_SET=<022> #optional
    volumes:
      - /home/nightcom/jellyfin/config:/config
      - /home/nightcom/jellyfin/lib:/opt/vc/lib #optional
      - /home/nightcom/jellyfin/multimedia:/data/multimedia
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
